server.port: 8181
spring.cloud.stream:
  bindings:
    outbound1:
      destination: topic1
  kafka.binder:
    configuration:
      commit.interval.ms: 1000
    brokers: localhost:9092
    serdeError: logAndContinue
  kafka.bindings:
    outbound1:
      producer:
        configuration:
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          spring.json.trusted.packages: '*'
          spring.json.value.default.type: csci318.demo.model.Appliance