server.port: 8183
spring.cloud.stream.bindings:
      inbound:
        destination: topic1
      outbound:
        destination: topic2
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    commit.interval.ms: 1000
  serdeError: logAndContinue
spring.cloud.stream.kafka.streams.bindings:
  inbound:
    consumer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: csci318.demo.model.Appliance
      #materializedAs: my-store1
  outbound:
    producer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: csci318.demo.model.Appliance

#spring.cloud.stream.kafka.streams.binder.stateStoreRetry.maxAttempts: 3



